title: プログラミング言語 Hinako
description: brainf*ckをベースに実装した、喜多日菜子(アイドルマスターシンデレラガールズのアイドル)の妄想でコードを書くプログラミング言語。
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed # フィード
  - jekyll-redirect-from # リダイレクト
  - jekyll-seo-tag # SEOタグ
  - jekyll-sitemap # サイトマップ
  - jemoji # 絵文字
  - jekyll-mentions # メンション